server:
  port: 9001
spring:
  application:
    name: getwayService
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    gateway:
      routes:
        - id: venueservice
          uri: lb://venue
          predicates:
            - Path=/venue/**
        - id: coachService
          uri: lb://coachService
          predicates:
            - Path=/coach/**

